# Generated by Django 3.1.5 on 2021-01-17 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='products.product'),
        ),
    ]
